<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>error_checkout</name>
   <tag></tag>
   <elementGuidId>331dc770-00d3-4c82-b8da-e598b03b8a52</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/h3[@data-test=&quot;error&quot;]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
