<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_checkout</name>
   <tag></tag>
   <elementGuidId>bd2eaa26-ee0c-47b3-ada1-8858f8d0d779</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/div[2]/span[contains(text(),&quot;Checkout&quot;)]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
