<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_checkout_overview</name>
   <tag></tag>
   <elementGuidId>6f0c8f4b-2a2d-4de7-8a69-20fe8f42249e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/span[contains(text(),'Overview')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
