<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_co_complete</name>
   <tag></tag>
   <elementGuidId>9b2cd036-a031-4f1e-9e4b-8c2b19b35daa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*/span[contains(text(),'Complete')]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
